import { Empty, Failed, Loading, Panel, when } from "@/components/admin/primitives";
import { useAdminAudit } from "@/lib/admin-hooks";

/**
 * The administrative trail.
 *
 * Reads are deliberately not recorded. Auditing every view of this screen
 * would bury the mutations that matter under noise generated by the page
 * built to display them.
 */
export function AdminAudit() {
  const q = useAdminAudit(200);

  if (q.isLoading) return <Panel title="Audit"><Loading label="Loading audit trail" /></Panel>;
  if (q.isError) return <Panel title="Audit"><Failed error={q.error} /></Panel>;

  const entries = q.data!.entries;
  if (entries.length === 0) {
    return (
      <Panel title="Audit">
        <Empty>No administrative actions recorded yet.</Empty>
      </Panel>
    );
  }

  return (
    <Panel title={`${entries.length} most recent actions`}>
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead className="border-b border-border text-left text-xs uppercase tracking-wider text-muted-foreground">
            <tr>
              <th className="px-5 py-2 font-semibold">When</th>
              <th className="px-5 py-2 font-semibold">Action</th>
              <th className="px-5 py-2 font-semibold">Target</th>
              <th className="px-5 py-2 font-semibold">Detail</th>
            </tr>
          </thead>
          <tbody>
            {entries.map((e, i) => (
              <tr key={e.id ?? i} className="border-b border-border/50 last:border-0 align-top">
                <td className="whitespace-nowrap px-5 py-2.5 text-xs text-muted-foreground">
                  {when(e.created_at)}
                </td>
                <td className="px-5 py-2.5 font-medium text-foreground">{e.action}</td>
                <td className="px-5 py-2.5 text-xs text-muted-foreground">{e.target ?? "—"}</td>
                <td className="px-5 py-2.5 text-xs text-muted-foreground">
                  {e.detail ? (
                    <code className="block max-w-md truncate" title={JSON.stringify(e.detail)}>
                      {JSON.stringify(e.detail)}
                    </code>
                  ) : (
                    "—"
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Panel>
  );
}
