#!/usr/bin/env python3
"""Generate platform/.env.production.local.

Run once. Secrets are generated here rather than pasted so they never pass
through a terminal, a chat window or shell history. Re-running overwrites the
file and rotates every generated secret, which would invalidate live sessions
and make already-encrypted tenant secrets unreadable — so it refuses unless
--force is given.
"""

from __future__ import annotations

import secrets
import sys
from pathlib import Path

from cryptography.fernet import Fernet

TARGET = Path(__file__).resolve().parent.parent / ".env.production.local"

TEMPLATE = """\
# ---------------------------------------------------------------------------
# Zeus Platform — PRODUCTION configuration. Generated by scripts/make_prod_env.py
#
# Gitignored. Never commit. These values also go into the Vercel project's
# environment variables; this file is the local source of truth for deploys.
# ---------------------------------------------------------------------------

ZEUS_ENV=production
ZEUS_LOG_LEVEL=INFO
ZEUS_DEV_TOKENS=false

# --- Signing + encryption (generated locally, NOT from any provider) -------
# ZEUS_SUPABASE_JWT_SECRET is a legacy name: it is the HS256 key our own
# AuthProvider signs access tokens with. We do not use Supabase Auth, so this
# must be our own secret. Rotating it invalidates every live access token.
ZEUS_SUPABASE_JWT_SECRET={jwt_secret}
# Encrypts admin-managed secrets at rest. Rotating it makes existing
# ciphertext unreadable, so treat it as permanent once data exists.
ZEUS_SECRETS_ENCRYPTION_KEY={fernet_key}
# Shared secret authenticating internal worker callbacks (queue -> HTTP).
ZEUS_WORKER_SECRET={worker_secret}

# --- Database -------------------------------------------------------------
# Both URLs go through Supabase's connection pooler. The direct host
# (db.<ref>.supabase.co) is IPv6-only on new projects and is unreachable from
# Vercel, so it is never used.
#
# Runtime uses the TRANSACTION pooler (:6543): serverless cold starts would
# otherwise exhaust Postgres connections. asyncpg must disable prepared
# statements against it (see the postgres adapter).
ZEUS_DATABASE_PROVIDER=postgres
ZEUS_DATABASE_URL={runtime_url}
# Serverless: each function instance needs only a couple of connections.
ZEUS_DATABASE_POOL_MIN=0
ZEUS_DATABASE_POOL_MAX=2

# Migrations use the SESSION pooler (:5432) — transaction mode cannot run DDL
# reliably. Not read by the app at runtime.
ZEUS_MIGRATE_URL={direct_url}

# --- Supabase (storage + project APIs; NOT auth) --------------------------
ZEUS_SUPABASE_URL={supabase_url}
ZEUS_SUPABASE_ANON_KEY={supabase_anon_key}
ZEUS_SUPABASE_SERVICE_ROLE_KEY={supabase_service_key}

# --- Storage --------------------------------------------------------------
ZEUS_STORAGE_PROVIDER=supabase
ZEUS_STORAGE_BUCKET=evidence
ZEUS_STORAGE_MAX_UPLOAD_MB=25

# --- Cache ----------------------------------------------------------------
# rediss:// (double s) — Upstash requires TLS.
ZEUS_CACHE_PROVIDER=redis
ZEUS_REDIS_URL={redis_url}

# --- Queue ----------------------------------------------------------------
ZEUS_QUEUE_PROVIDER=qstash
ZEUS_QSTASH_URL={qstash_url}
ZEUS_QSTASH_TOKEN={qstash_token}
# Verify QStash request signatures so only Upstash can trigger our jobs.
ZEUS_QSTASH_CURRENT_SIGNING_KEY={qstash_sig_current}
ZEUS_QSTASH_NEXT_SIGNING_KEY={qstash_sig_next}

# --- Sessions -------------------------------------------------------------
# cookie_secure is forced true in production regardless; stated for clarity.
ZEUS_SESSION_COOKIE_SECURE=true
ZEUS_SESSION_COOKIE_SAMESITE=lax
# Leave unset while on *.vercel.app. Set to .zeusconsultingservices.com only
# once both console and API are served from that domain.
# ZEUS_SESSION_COOKIE_DOMAIN=.zeusconsultingservices.com
ZEUS_SESSION_TTL_DAYS=14

# --- LLM ------------------------------------------------------------------
ZEUS_LLM_PROVIDER=openai
ZEUS_LLM_MODEL=gpt-5-mini
ZEUS_OPENAI_API_KEY={openai_key}

# --- Billing --------------------------------------------------------------
ZEUS_BILLING_PROVIDER=stripe
ZEUS_STRIPE_SECRET_KEY={stripe_secret_key}
# Generated when the webhook endpoint is registered — needs the deployed URL,
# so it is filled in after the first deploy.
ZEUS_STRIPE_WEBHOOK_SECRET={stripe_webhook_secret}
"""

# Provider credentials are read from an untracked file rather than embedded
# here. They used to be inline constants, which meant this script — a tracked
# file — carried a live QStash token and database password into git history.
# Anything left as a TODO marker is reported by scripts/check_prod_env.py
# rather than failing silently at boot.
PROVIDERS = Path(__file__).resolve().parent.parent / ".env.providers.local"

REQUIRED_KEYS = (
    "supabase_url",
    "supabase_anon_key",
    "supabase_service_key",
    "direct_url",
    "runtime_url",
    "redis_url",
    "qstash_url",
    "qstash_token",
    "qstash_sig_current",
    "qstash_sig_next",
)

# Filled in later, so a missing value is a placeholder rather than an error.
OPTIONAL_KEYS = {
    "openai_key": "TODO_PASTE_OPENAI_API_KEY",
    "stripe_secret_key": "TODO_PASTE_STRIPE_SECRET_KEY",
    "stripe_webhook_secret": "TODO_AFTER_FIRST_DEPLOY",
}

PROVIDERS_TEMPLATE = """# Provider credentials for scripts/make_prod_env.py.
# Untracked (.gitignore covers .env.*). Never paste these into a tracked file.
supabase_url=
supabase_anon_key=
supabase_service_key=
# Admin role, session pooler :5432 — DDL/migrations only.
direct_url=
# Least-privilege app role (zeus_app), transaction pooler :6543 — runtime.
# MUST NOT be the 'postgres' superuser: it has BYPASSRLS, which would silently
# defeat every row-level tenant isolation policy.
runtime_url=
redis_url=
qstash_url=https://qstash-us-east-1.upstash.io
qstash_token=
qstash_sig_current=
qstash_sig_next=
"""


def load_providers() -> dict[str, str]:
    if not PROVIDERS.exists():
        PROVIDERS.write_text(PROVIDERS_TEMPLATE, encoding="utf-8")
        PROVIDERS.chmod(0o600)
        raise SystemExit(
            f"Created {PROVIDERS.name}. Fill in the provider credentials there, "
            "then re-run this script."
        )

    values: dict[str, str] = dict(OPTIONAL_KEYS)
    for line in PROVIDERS.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, value = line.partition("=")
        value = value.strip()
        if value:
            values[key.strip()] = value

    missing = [k for k in REQUIRED_KEYS if not values.get(k)]
    if missing:
        raise SystemExit(f"{PROVIDERS.name} is missing: {', '.join(missing)}")

    # Supabase's 'postgres' role carries BYPASSRLS and cannot be altered on a
    # managed instance. If it ever becomes the runtime DSN, every tenant
    # isolation policy is silently skipped and nothing fails loudly. Refuse.
    runtime_user = values["runtime_url"].split("://", 1)[-1].split(":", 1)[0]
    if runtime_user.split(".", 1)[0] == "postgres":
        raise SystemExit(
            "runtime_url uses the 'postgres' role, which has BYPASSRLS and would "
            "defeat tenant isolation. Use the zeus_app role "
            "(see scripts/provision_db_role.py)."
        )
    return values


def main() -> int:
    if TARGET.exists() and "--force" not in sys.argv:
        print(f"{TARGET.name} already exists. Re-run with --force to regenerate.")
        print("Warning: regenerating rotates the JWT and encryption keys, which")
        print("logs everyone out and orphans any already-encrypted secrets.")
        return 1

    content = TEMPLATE.format(
        jwt_secret=secrets.token_urlsafe(48),
        fernet_key=Fernet.generate_key().decode(),
        worker_secret=secrets.token_urlsafe(32),
        **load_providers(),
    )
    TARGET.write_text(content)
    TARGET.chmod(0o600)
    print(f"Wrote {TARGET}")
    print("Secrets generated: ZEUS_SUPABASE_JWT_SECRET, ZEUS_SECRETS_ENCRYPTION_KEY,")
    print("ZEUS_WORKER_SECRET. Run scripts/check_prod_env.py to see what is still TODO.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
